### ISSUE TITLE
Bug: The example does not work

### ISSUE THREAD

**Issue by pamplins** [bytemechanics/type-ex#10]
We created the following exception enum:

```Java
package com.allianz.ebcm.cli.exceptions;

import org.bytemechanics.typeex.ExceptionType;
import org.bytemechanics.typeex.impl.TypifiedException;

public enum GenericException implements ExceptionType {
	TEST("Message here {}");	

	private final String message;
	
	GenericException(final String _message){
		this.message=_message;
	}		
	@Override
	public String getMessage() {
		return this.message;
	}
}
```

But when we try to use:

```Java
throw GenericException.TEST.get();
```

The compiler throws `No exception of type TypifiableException can be thrown; an exception type must be a subclass of Throwable`

**Comment by watarhu** [comment]
True enough. The documentation is wrong. 

You need to point the generic type into the ExceptionType interface in order to propagate the type to the get() method otherwise the compiler sees only the interface that effectively didn't implement Throwable because is an abstract class not an interface and can no be extended by an interface.

In your example you need to change:
```diff
package com.allianz.ebcm.cli.exceptions;

import org.bytemechanics.typeex.ExceptionType;
import org.bytemechanics.typeex.impl.TypifiedException;

- public enum GenericException implements ExceptionType {
+ public enum GenericException implements ExceptionType<TypifiedException> {
	TEST("Message here {}");	

	private final String message;
	
	GenericException(final String _message){
		this.message=_message;
	}		
	@Override
	public String getMessage() {
		return this.message;
	}
}
```

Also updated documentation readme and wiki

**Comment by watarhu** [comment]
I hope this solves your issue.
